import raw from '../data/leetcode.json';

type LeetCodeData = {
  generatedAt: string;
  username: string;
  profileUrl: string;
  solved: number;
  totalQuestions: number;
  difficulties: { name: string; solved: number; total: number }[];
  ranking: number | null;
  badges: string[];
  calendarYear: number;
  activeDays: number;
  maxStreak: number;
};

/** Generated by `npm run fetch:github` (scripts/fetch-github.js). */
export const leetcode = raw as LeetCodeData;
